[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
rust_decimal = { workspace = true }

[[test]]
name = "fifo_tests"
path = "tests/matching_logic/fifo_tests.rs"
